# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('preferred_formation', models.CharField(max_length=10)),
                ('win_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coach_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Coach')),
            ],
        ),
        migrations.CreateModel(
            name='Coaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_ends', models.DateField()),
                ('coach_term', models.DurationField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Coach')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('GK', 'Goleiro'), ('RB', 'Lateral direito'), ('CB', 'Zagueiro'), ('LB', 'Lateral esquerdo'), ('CM', 'Volante'), ('AM', 'Meia avancado'), ('RM', 'Ponta direita'), ('LM', 'Ponta esquerda'), ('CF', 'Atacante')], max_length=100)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dominant_foot', models.CharField(choices=[('R', 'Destro'), ('L', 'Canhoto')], max_length=100)),
                ('shirt_number', models.IntegerField(blank=True, null=True)),
                ('agent', models.CharField(blank=True, max_length=100, null=True)),
                ('url_profile', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Plays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_ends', models.DateField()),
                ('on_loan', models.BooleanField(default=False)),
                ('is_capitan', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nameCompleto', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('badge', models.ImageField(upload_to='assets/badges')),
                ('imagemCamisa', models.ImageField(upload_to='assets/shirts')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('date', models.DateField()),
                ('is_top', models.BooleanField(default=False)),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_destiny', to='core.Team')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_origin', to='core.Team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Player')),
            ],
        ),
        migrations.AddField(
            model_name='plays',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
        migrations.AddField(
            model_name='player_history',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
        migrations.AddField(
            model_name='coaches',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
        migrations.AddField(
            model_name='coach_history',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
    ]
