# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160502_1109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player_History',
            new_name='History',
        ),
        migrations.RemoveField(
            model_name='coach_history',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='coach_history',
            name='team',
        ),
        migrations.AlterField(
            model_name='coach',
            name='win_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='plays',
            name='contract_ends',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='badge',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='kit_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Coach_History',
        ),
    ]
