# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160507_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coaches',
            name='contract_ends',
            field=models.DateField(null=True),
        ),
    ]
