# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160507_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name': 'Treinador', 'verbose_name_plural': 'Treinadores'},
        ),
        migrations.AlterModelOptions(
            name='coaches',
            options={'verbose_name': 'Treina', 'verbose_name_plural': 'Treina'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'Historico', 'verbose_name_plural': 'Historicos'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Jogador', 'verbose_name_plural': 'Jogadores'},
        ),
        migrations.AlterModelOptions(
            name='plays',
            options={'verbose_name': 'Joga', 'verbose_name_plural': 'Joga'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Time', 'verbose_name_plural': 'Times'},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'verbose_name': 'Transferencia', 'verbose_name_plural': 'Transferencia'},
        ),
    ]
