# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160507_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coaches',
            name='coach_term',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coaches',
            name='contract_ends',
            field=models.DateField(blank=True, null=True),
        ),
    ]
