# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160507_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='win_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='plays',
            name='contract_ends',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_origin', to='core.Team'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
