# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160507_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coaches',
            name='coach_term',
        ),
        migrations.RemoveField(
            model_name='coaches',
            name='contract_ends',
        ),
        migrations.RemoveField(
            model_name='plays',
            name='contract_ends',
        ),
        migrations.RemoveField(
            model_name='plays',
            name='is_capitan',
        ),
        migrations.RemoveField(
            model_name='plays',
            name='on_loan',
        ),
        migrations.RemoveField(
            model_name='team',
            name='kit_image',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='is_top',
        ),
    ]
