# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160529_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
