# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_player_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Goleiro'), ('RB', 'Lateral direito'), ('CB', 'Zagueiro'), ('LB', 'Lateral esquerdo'), ('DM', 'Volante'), ('CM', 'Meia central'), ('AM', 'Meia avancado'), ('RM', 'Ponta direita'), ('LM', 'Ponta esquerda'), ('CF', 'Atacante')], max_length=100, null=True),
        ),
    ]
